### ISSUE TITLE
Can I have the pre-trained weight for the model?

### ISSUE THREAD

**Issue by IndikaWeerakoon** [ezavarygin/PConv2D_Keras#1]
I tried your network with my own data set, but i didn't get much accurate result. @ezavarygin  appreciate if you could provide your trained weight compare with my result. 

thank you

**Comment by ezavarygin** [comment]
The link to the weights is given in the Training section of README, duplicating it [here](https://drive.google.com/file/d/1XdcKQASsa8mtpPIt3aAkcvije0U1J2Fy/view).
Note, I could not get the same quality as was demonstrated in the paper so your result might be consistent with mine. Let me know if you find a solution.

**Comment by IndikaWeerakoon** [comment]
Yes, I found your trained data set. thank you so much.
